### ISSUE TITLE
Specify patch for genomes

### ISSUE THREAD

**Issue by ihodes** [hammerlab/biokepi#100]
We need to be able to use e.g. patch 4 for grch38.

**Comment by arahuja** [comment]
Are you thinking of making this a property of each reference? Or just as separate references?  I guess part of this is done implictly in that the link specifies a version of each reference, but don't record which.

Do the dbsnp files change per patch as well?  Just asking question out loud really...

**Comment by ihodes** [comment]
An easy fix would be to just specify the patch in the reference name/type; I don't really have a preference, though.

Not sure re: dbsnp /cc @iskandr?

**Comment by smondet** [comment]
i don't know exactly what a reference patch looks like, but if the patch adds or removes a single base-pair the VCF will be wrong, won't it?

I think the patches should be separate reference genomes (if the patch is distributed as a `.diff`-like then the workflow-node that downloads it can depend on the original un-patched version).

**Comment by iskandr** [comment]
@smondet Patches don't ever change the coordinate system, but can change the nucleotide values at particular coordinates (I think the most common case is filling in N's). They also can add alternative contigs. 

I haven't seen anything like a diff for the genome, they also seem to be distributed as distinct FASTA files, with distinct derived files like transcriptome FASTAs.

**Comment by iskandr** [comment]
@arahuja It looks like dbSNP releases are specific to GRCh37 and GRCh38 patches, see: ftp://ftp.ncbi.nih.gov/snp/release-notes/Build144/human_ftp_directory_change.txt

**Comment by smondet** [comment]
OK, patches are different genomes, closing :ticket:
