### ISSUE TITLE
Add HISAT2 Graph-aligner, human and murine reference graphs

### ISSUE THREAD

**Issue by JPFinnigan** [hammerlab/biokepi#102]
Would be great if this were implemented. Per the creators, it's a recommended upgrade for all users HISAT and/or TopHat. 

Link: https://ccb.jhu.edu/software/hisat2/index.shtml

Reference graphs: https://ccb.jhu.edu/software/hisat2/index.shtml

**Comment by arahuja** [comment]
Closed by #219
