### ISSUE TITLE
Unclear exception on bad workdir name

### ISSUE THREAD

**Issue by ihodes** [hammerlab/biokepi#105]
I am creating a compiler in a workflow, like so:

```ocaml
Compiler.create
      ~machine:Demeter.machine
      ~processors:24
      ~work_dir:"mm10_test"
      ~reference_build:`mm10 ()
```

But since `~work_dir` is a relative path, I get the below exception. In a pile of code, I have no idea where this is coming from. It could be made more clear by telling me that `work_dir` needs to be an absolute path.

```
biokepi-debug: Result_Prefix: "mm10_test/dataset-bwa-mem-gap11-gep4"
biokepi-debug: Result_Path: "mm10_test/dataset-R1-cat.fastq"
Exception: Invalid_argument "[\"Path\"]: absolute_directory_exn".
```

**Comment by smondet** [comment]
Thanks I moved it there: https://github.com/hammerlab/ketrew/issues/303
