### ISSUE TITLE
Upgrade to Mutect2

### ISSUE THREAD

**Issue by arahuja** [hammerlab/biokepi#109]
Released in beta late last year: https://www.broadinstitute.org/gatk/blog?id=6495

This is an interesting one to upgrade since it relies on an external JAR. Also, I'm not sure how we are handling installing tools with different versions. I know we can set it in the `Tool` defintion, but in the end we create a directory called `mutect` without a version - should that be updated?

Lastly, if we wanted to create a pipeline to compare too versions, we would need to include the versions in the filename?

**Comment by timodonnell** [comment]
+1 It would be great to be able to compare against Mutect2.

Haven't been able to find the source code but here are the docs for future reference: https://www.broadinstitute.org/gatk/guide/tooldocs/org_broadinstitute_gatk_tools_walkers_cancer_m2_MuTect2.php

**Comment by smondet** [comment]
So the idea is to get GATK 3.5, and Mutect2 will some class in the `.jar`?

**Comment by iskandr** [comment]
Source: https://github.com/broadgsa/gatk-protected/blob/e91472ddc7d58ace52db0cab4d70a072a918d64c/protected/gatk-tools-protected/src/main/java/org/broadinstitute/gatk/tools/walkers/cancer/m2/MuTect2.java

Looks like it's more closely integrated into GATK and possibly rewritten. Not sure if this implements the same variant calling logic as the original Mutect.

**Comment by smondet** [comment]
This was merged a while ago.
