### ISSUE TITLE
Input Bams should be linked (`ls -s`)

### ISSUE THREAD

**Issue by smondet** [hammerlab/biokepi#112]
Here https://github.com/hammerlab/biokepi/blob/master/src/lib/pipeline.ml#L511

If we give bams that are not indexed, `samtools` will index them in place which breaks the assumption that Biokepi does everything inside its playground.

**Comment by arahuja** [comment]
I think we discussed this earlier as well. How strong is this assumption? Isn't the same true for sorting? https://github.com/hammerlab/biokepi/blob/master/src/lib/samtools.ml#L120-L121

**Comment by smondet** [comment]
Yes I remember discussing it; but could not find an issue; so since I had that specific example; I wrote it there.
We should find a general solution to all these particular problems :)
