### ISSUE TITLE
Ensure result directories exist

### ISSUE THREAD

**Issue by arahuja** [hammerlab/biokepi#12]
The first step of many variant callers is 
```
&& shf "cd %s" Filename.(dirname result_prefix)
```
where `Filename.(dirname result_prefix)` may not exist. The open is question is whether the task should create the directory or fail if it does not exist

**Comment by smondet** [comment]
I think we can add `mkdir -p`s everywhere (there are already some).

**Comment by arahuja** [comment]
yea, looking at it, looks most of the others already have it
