### ISSUE TITLE
MOSAIK aligner

### ISSUE THREAD

**Issue by iskandr** [hammerlab/biokepi#120]
Paper: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0090581

Repo: https://github.com/wanpinglee/MOSAIK

It's unclear if this aligner is still under development and there are a few worrying segfault issues on the github page. Nonetheless, we need to test it out.

**Comment by smondet** [comment]
This is there: https://github.com/hammerlab/biokepi/pull/69

**Comment by iskandr** [comment]
Awesome!

**Comment by arahuja** [comment]
Wow, didn't remember!
