### ISSUE TITLE
Add Kallisto to Pipeline DSL

### ISSUE THREAD

**Issue by ihodes** [hammerlab/biokepi#139]
https://pachterlab.github.io/kallisto/about.html

**Comment by arahuja** [comment]
@ihodes: https://github.com/hammerlab/biokepi/pull/77

**Comment by ihodes** [comment]
Awesome! It's like you read my mind in the future from the past. Let me amend this issue; we still need it in the pipeline DSL.

**Comment by arahuja** [comment]
Started poking at this last night and some ideas on what you were thinking @smondet @ihodes would be appreciated.

The main issue is that Kallisto (and I'm sure others e.g. Topiary, hla typing) doesn't result in a 'common' output like fastq or bam, but just a text/csv file. Should this result in a new type and new compilation function every time? I saw that seq2hla just had it's own output type added. Should pipeline start to split out and become more specialized?

**Comment by smondet** [comment]
@arahuja yes new file-type, means new type, means new toplevel `Compiler` function
My take was to wait for the reimplementation of `Pipeline` as a more extensible/modular EDSL.

Since, for now Kallisto is always at the end of a pipeline, users can use the `Kallisto` module directly without much loss.

But if you implement it, it will useful (and reused in the reimplementation anyway).

**Comment by arahuja** [comment]
> Since, for now Kallisto is always at the end of a pipeline, users can use the Kallisto module directly without much loss.

Yes, that's how I worked around this for now. 

```
let pipeline = 
    Biokepi.Pipeline.Construct.(
          bam ~dataset:sample initial_bam
          |> bam_to_fastq `Paired
        )
  in
  let fastq =
    let compiler =
      Compiler.create ()
        ~processors:8
        ~reference_build
        ~work_dir
        ~machine: Demeter.machine
    in
    Compiler.fastq_sample_step ~compiler pipeline   
  in
  Biokepi.Kallisto.run
    ~reference_build
    ~run_with: Demeter.machine
    ~bootstrap_samples:100
    ~processors:8
    ~fastq
    ~result_prefix: (work_dir // sample)
```
