### ISSUE TITLE
Set SM in bwa aligner

### ISSUE THREAD

**Issue by arahuja** [hammerlab/biokepi#154]
Currently in the BWA aligners (`aln` and `mem`) we set the `SM` or sample field as `SM`. 

https://github.com/hammerlab/biokepi/blob/master/src/lib/bwa.ml#L45-L47

Since every BAM file has `SM` set the same downstream tools don't properly set SM fields, i.e. Mutect will not give a column per sample in the VCF

**Comment by iskandr** [comment]
Just hit this. 

Are we at least guaranteed that SM is always the normal sample? 

Also, it would be good to eventually get `TUMOR` and `NORMAL` as separate sample columns.

**Comment by arahuja** [comment]
Are we at least guaranteed that SM is always the normal sample?
@iskandr funny enough, I don't think you are, it's random I think, as one just overwrites the other, but not sure.
