### ISSUE TITLE
Quick_run_program vs. Run_program

### ISSUE THREAD

**Issue by ihodes** [hammerlab/biokepi#163]
When we use `Quick_run_program` internally, we use it with the implicit assumption that commands it executes have internet access, whereas `Run_program` does not. This is because our compute nodes don't have internet access (they shouldn't). However, this is really overloading the API (`Quick_run_program` is about running short-lived commands that don't require much config, not about internet access), and manifests in Biokepi by virtue of the fact that all tool installers from `Tool_providers` use `Quick_run_program`. 

We should encode the requirement of internet connectivity in the type system, and let `Quick_run_program` and `Run_program` determine how to dispatch commands which require the internet.

**Comment by smondet** [comment]
Yes! We could even merge the two functions and let the implementation decide what to do depending on the requirements specified in the arguments.

**Comment by ihodes** [comment]
That would be awesome, highly in favor of that option.

**Comment by ihodes** [comment]
Tools should be able to request internet access, a YARN cluster (that can e.g. run a Spark job), maybe GPUs, minimum memory requirements, etc.

**Comment by iskandr** [comment]
:+1: To merging `Run_program` and `Quick_run_program`

**Comment by ihodes** [comment]
This has been fixed in #180
