### ISSUE TITLE
Samtools.merge can result in malformed SAMs

### ISSUE THREAD

**Issue by ihodes** [hammerlab/biokepi#167]
I have headers that have the `@PG` group appearing multiple times with the same ID, which is bad according to the [spec](https://samtools.github.io/hts-specs/SAMv1.pdf). Picard dies on this, so we can't mark dups. According to [samtool's docs](http://www.htslib.org/doc/samtools.html), this shouldn't be the case: the IDs should be automatically uniquified.

**Comment by iskandr** [comment]
@ihodes Are we merging with `-c` and `-p`? From the docs:

>**-c**
>When several input files contain @RG headers with the same ID, emit only one of them (namely, the header line from the first file we find that ID in) to the merged output file. Combining these similar headers is usually the right thing to do when the files being merged originated from the same file.

>Without -c, all @RG headers appear in the output file, with random suffices added to their IDs where necessary to differentiate them.

>**-p**
>Similarly, for each @PG ID in the set of files to merge, use the @PG line of the first file we find that ID in rather than adding a suffix to differentiate similar IDs.

**Comment by ihodes** [comment]
Nope; per the doc: we shouldn't have to use -p and -c (but now we will to get around this):

> Unless the -c or -p flags are specified then when merging @RG and @PG records into the output header then any IDs found to be duplicates of existing IDs in the output header will have a suffix appended to them to diffientiate [sic] them from similar header records from other files and the read records will be updated to reflect this.

**Comment by iskandr** [comment]
Huh, and yet we don't get a unique suffix. That's very strange.
