### ISSUE TITLE
Implement parallelization for IndelRealigner

### ISSUE THREAD

**Issue by ihodes** [hammerlab/biokepi#185]
cf. http://gatkforums.broadinstitute.org/wdl/discussion/1988/a-primer-on-parallelism-with-the-gatk

**Comment by ihodes** [comment]
We can apparently just scatter-gather IndelRealigner, according to the above source.

This would be a massive win, as in our current pipeline this step currently takes 20 hrs and will grow significantly with the addition of high-coverage BAMs.

**Comment by hammer** [comment]
Can also be done with Spark
