### ISSUE TITLE
Input_fastq type

### ISSUE THREAD

**Issue by rleonid** [hammerlab/biokepi#195]
In [Pipeline](https://github.com/hammerlab/biokepi/blob/master/src/lib/pipeline.ml#L90)
 
1. The name of this type makes more sense as a noun, fastq_input.
2. `Paired_end should contain (File.t * File.t) list ... since they are paired.
3. There needs to be a simpler type of `Single_pair and `Paired_type renamed.

**Comment by smondet** [comment]
This is fixed in the EDSL library.
