### ISSUE TITLE
Machine should handle ~processors, not Compiler

### ISSUE THREAD

**Issue by ihodes** [hammerlab/biokepi#201]

**Comment by ihodes** [comment]
processors should be specified like so

```ocaml
Machine.run_program ~requirements:[`Processors n]
```

**Comment by smondet** [comment]
In this case we also need a `Machine.max_processors` query, so that the Biokepi tool can “clip” its requirements in the `Program.t` also (the `-p` or `-nt` arguments have to be consistent to be a good citizen).

**Comment by smondet** [comment]
This has been done for a while.
