### ISSUE TITLE
Align directly from compressed FASTQ files

### ISSUE THREAD

**Issue by iskandr** [hammerlab/biokepi#222]
The [starter example](https://github.com/lh3/bwa/blob/master/README.md) for BWA-MEM takes compressed inputs and pipes to compressed output. If we do this in Biokepi we can possibly skip the gunzip step and save space:

```./bwa mem ref.fa read-se.fq.gz | gzip -3 > aln-se.sam.gz```

**Comment by smondet** [comment]
We do a bunch of those piping hacks, + with parallelization, alignment is really not the bottleneck.
