### ISSUE TITLE
seq2hla installation fails

### ISSUE THREAD

**Issue by arahuja** [hammerlab/biokepi#247]
stdout
```
Checking for available remotes: rsync and local, git, mercurial.
  - you won't be able to use darcs repositories unless you install the darcs
    command on your system.


=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[biopam: git]
[biopam: git]
[biopam: git]
[biopam: git]
[biopam: git]
[biopam: git]
[biopam] https://github.com/solvuu/biopam.git updated
OpamGlobals.Exit(66)
```

stderr 
```
[WARNING] External solver failed with inconsistent return value. Request saved
          to
          "/demeter/scratch/ahujaa01/ksinai-demeter/biopam/opam_dir/.opam/log/solver-error-33663-1.cudf"
[ERROR] External solver failure, please fix your installation and check
        /demeter/scratch/ahujaa01/ksinai-demeter/biopam/opam_dir/.opam/config
        and variable $OPAMEXTERNALSOLVER.
        You may also retry with option --use-internal-solver
[ERROR] Initialisation failed
```

This seems like it is relying on a biokepi managed `opam` as opposed to the one installed on the machine. Is there other config needed?

**Comment by smondet** [comment]
@arahuja do you have `aspcud` in your path?

Maybe it's interacting with the calls to `opam` within biokepi.

@rleonid any ideas?

**Comment by rleonid** [comment]
What's the contents of the `cudf` file?  I haven't needed on `aspucd` on Linux, once I installed `opam` from the release like we do in `biokepi`.

**Comment by arahuja** [comment]
@rleonid I'm not sure what file to check. Is the `.opam` file removed if this fails?

**Comment by rleonid** [comment]
@arahuja `/demeter/scratch/ahujaa01/ksinai-demeter/biopam/opam_dir/.opam/log/solver-error-33663-1.cudf`

It is a readable format http://www.mancoosi.org/cudf/primer/, maybe we can figure out why the solver failed.

**Comment by rleonid** [comment]
I would grab the file, but it is missing. Not certain why it was removed.

**Comment by smondet** [comment]
The `.opam` should be there, the configuration does not clean-up after running:
https://github.com/hammerlab/biokepi/blob/779e1df4acf47c294ace8581b1b6ad982cef6ba3/src/environment_setup/biopam.ml#L103

**Comment by rleonid** [comment]
I don't know what happened:
```
hammerlab-dev2:~$ ls -la /demeter/scratch/ahujaa01/ksinai-demeter/biopam/opam_dir/
total 6120
drwxr-xr-x 2 ahujaa01 hammej03a      17 Apr 19 23:30 .
drwxr-xr-x 4 ahujaa01 hammej03a     101 Apr 19 23:30 ..
-rwxr-xr-x 1 ahujaa01 hammej03a 6265225 May  7  2015 opam
```

**Comment by arahuja** [comment]
Yea, I did not remove the directory manually at least. Also should Miniconda be in the biopam dir?

**Comment by arahuja** [comment]
> @arahuja do you have aspcud in your path?

@smondet I do, would that affect something?

**Comment by smondet** [comment]
@arahuja At least, that may give a different environment for different people. Do you have the aspcud, the actual solver, or is it the proxy-script renamed to `aspcud`?

**Comment by arahuja** [comment]
Proxy script

**Comment by arahuja** [comment]
Crazy, I just re-ran ... works. No changes. Will close for now
