### ISSUE TITLE
Make processors a max_procesors argument to a machine

### ISSUE THREAD

**Issue by arahuja** [hammerlab/biokepi#25]
Something we had discussed before, but most of the tools take a `processors` argument.  Some of the tools don't support it but steps in their pipeline might.  Alot of these tools default to 1 or drop the argument at some point, but this can lead to some oddities, i.e if I submit a variant caller run with `mutect`, the `samtools sort` step will happen with 2 threads, while with `strelka` it will happen with has many `processors` I gave `strelka`

**Comment by smondet** [comment]
This was done a while ago :)
