### ISSUE TITLE
mm10's reference genome and gene annotations are of different Ensembl releases

### ISSUE THREAD

**Issue by armish** [hammerlab/biokepi#279]
[reference_genome.ml#L170](https://github.com/hammerlab/biokepi/blob/master/src/run_environment/reference_genome.ml#L170) (release `84`) 
**vs** 
[reference_genome.ml#L179](https://github.com/hammerlab/biokepi/blob/master/src/run_environment/reference_genome.ml#L179)  (release `79`)

Was this done on purpose or should we sync them up?

**Comment by ihodes** [comment]
Definitely an oversight; no reason to not have them be the same/more recent. Thanks for catching!
