### ISSUE TITLE
Sort and convert sam to bam simultaneously

### ISSUE THREAD

**Issue by arahuja** [hammerlab/biokepi#29]
An unsorted bam is much larger than a sorted one and we can avoid the intermediate file by piping the commands together since almost every tools needs a sorted bam

**Comment by arahuja** [comment]
@ihodes @smondet This might be a way to save some space/time and time on an alignment pipeline? Not writing the original SAM ever would be a large savings of space

**Comment by smondet** [comment]
It might save some time but the `sam` file is already deleted after `sam-to-bam`.

**Comment by arahuja** [comment]
It would save space while running since it would never create the uncompressed output
