### ISSUE TITLE
Non-intuitive module names -> paths

### ISSUE THREAD

**Issue by ihodes** [hammerlab/biokepi#301]
When looking at code like `open Biokepi.Edsl.Library.Input` and trying to figure out where it comes from, it's not the simplest path from there to `/src/pipeline_edsl/pipeline_library.ml` and the submodule `Input` contained therein.

**Comment by smondet** [comment]
You should only need the documentation :)
http://www.hammerlab.org/biokepi/ (a couple of weeks outdated, but `Biokepi.EDSL.Library.Input` is there)

Yes, there is a lot of module mangling to make the API nicer, I don't know how to simplify that.

**Comment by ihodes** [comment]
I need to remember to use the docs more (though looking directly at the code is often more useful for me).

Would it be possible to rename e.g. pipeline_edsl -> edsl, and pipeline_library.ml -> library.ml?
