### ISSUE TITLE
BWA success condition is not strong enough

### ISSUE THREAD

**Issue by arahuja** [hammerlab/biokepi#312]
The success condition for BWA is currently that the output BAM exists, however the output BAM is the results of stdout redirect, so it will exist no matter what, even on command failure or interruption.

**Comment by smondet** [comment]
When BWA fails (i.e. returns non 0), the deletion of the SAM file should be triggered:
https://github.com/hammerlab/biokepi/blob/master/src/bfx_tools/bwa.ml#L214

How did you experience the problem?
(It can be with a manual restart from the Ketrew UI, or some other interuption of the workflow)

We can make this stronger though with `bwa ... > tmp-file` and then `mv tmp-file foo.sam`.

**Comment by arahuja** [comment]
It was from giving the wrong arguments in #309

**Comment by arahuja** [comment]
I think another time this came up was when I ran out of disk space, still investigating though
