### ISSUE TITLE
Add HLA typing

### ISSUE THREAD

**Issue by arahuja** [hammerlab/biokepi#33]
Tools to consider adding:
- [seq2hla](https://bitbucket.org/sebastian_boegel/seq2hla)
- [OptiType](https://github.com/FRED-2/OptiType)
- [ATHALETES](https://www.broadinstitute.org/scientific-community/science/projects/viral-genomics/athlates)

**Comment by ihodes** [comment]
We *need* Optitype & Seq2HLA.

**Comment by ihodes** [comment]
Closed by https://github.com/hammerlab/biokepi/pull/194 and https://github.com/hammerlab/biokepi/pull/221 and a bunch of subsequent PRs
