### ISSUE TITLE
BQSR keeps hitting missing file 

### ISSUE THREAD

**Issue by arahuja** [hammerlab/biokepi#35]
`BaseRecalibrator` seems to run but then the recal table file is missing?  @seb has this worked for you before? 
```
INFO  13:48:34,132 HelpFormatter - Program Args: -T BaseRecalibrator -I /hpc/users/ahujaa01/ksinai-demeter/work/path/pt189_bwa-mem-gap11-gep4-sorted.bam -R /hpc/users/ahujaa01/ksinai-demeter/B37-reference-genome/b37.fasta -knownSites /hpc/users/ahujaa01/ksinai-demeter/B37-reference-genome/dbsnp.vcf -o /hpc/users/ahujaa01/ksinai-demeter/work/PT189-B37/pt189-bwa-mem-gap11-gep4-recal_data.table


INFO  08:11:58,496 BaseRecalibrator - Writing recalibration report...
INFO  08:11:59,798 BaseRecalibrator - ...done!

INFO  08:12:02,994 HelpFormatter - Program Args: -T PrintReads -R /hpc/users/ahujaa01/ksinai-demeter/B37-reference-genome/b37.fasta -I /hpc/users/ahujaa01/ksinai-demeter/work/PT189-B37/pt189-bwa-mem-gap11-gep4-sorted.bam -BQSR /hpc/users/ahujaa01/ksinai-demeter/work/PT189-B37/pt189-bwa-mem-gap11-gep4-recal_data.table -o /hpc/users/ahujaa01/ksinai-demeter/work/PT189-PT189--B37/pt189-bwa-mem-gap11-gep4-bqsr.bam
```

There are many calls to ```INFO  08:12:00,701 HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Network is unreachable
INFO  08:12:00,702 HttpMethodDirector - Retrying request``` due to the ET call.  We can set the NO_ET flag if we have a key file to use

**Comment by smondet** [comment]
This I/O error is fine (I think); BQSR tries to phone home, to give statistics to the Broad unless you have license key.
We run it on a cluster than cannot access the web, but it usually still works.

The table, in the other hand, should be there
https://github.com/hammerlab/biokepi/blob/21fbdfbfd7214eacfbec0b248e62fbb1805ca93a/src/lib/biokepi_util_targets.ml#L272
do you have the target failing?

If BQSR failed for some other reason, it will be deleted:
https://github.com/hammerlab/biokepi/blob/21fbdfbfd7214eacfbec0b248e62fbb1805ca93a/src/lib/biokepi_util_targets.ml#L288

**Comment by arahuja** [comment]
I haven't hit this again - most of this were displaying with the "Starting timed out" issue in the ketrew UI, but the logs had the mention of the missing file.  Not sure what could have been at play here - ketrew starting cleanup, thinking the container hadn't started and then the container missing the data?  Either way seems to be resolved now.
