### ISSUE TITLE
OptiType does not use razerS3 to filter to HLA reads prior to running

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/biokepi#423]
Per the README, and sounds like @rleonid has always done this:

> Optional step zero: you might want to filter your sequencing data for HLA reads. Should you have to re-run OptiType multiple times on the same sample (different settings, etc.) it could save you time if instead of giving OptiType the full, multi-gigabyte sequencing data multiple times, you would rather give it the relevant reads only, on the order of megabytes.

Razers3 is called internally in https://github.com/FRED-2/OptiType/blob/master/OptiTypePipeline.py but that appears to not be doing the same thing (note `-m 99999`, for example).

**Comment by tavinathanson** [comment]
Re whether this could impact the results, from @rleonid:

> Results: (AFAIK) theoretically, no. But practically, I wouldn’t be surprised if numerically there are some issues.

**Comment by rleonid** [comment]
I'd like to recluse myself from being the judge/authority on constraint solvers. I've implemented toy simplex solvers but I don't know what kind of heuristics modern solvers might use.

**Comment by tavinathanson** [comment]
Possible, but seems unlikely to me, that this could address the memory issues in #419.

**Comment by tavinathanson** [comment]
@ihodes I'll try the pre-filtering manually on 30GB RAM and see what happens.

**Comment by tavinathanson** [comment]
Discussed offline: pre-filtering manually with 30GB of RAM also ran out of memory.

**Comment by ihodes** [comment]
Closing for https://github.com/hammerlab/biokepi/issues/426
