### ISSUE TITLE
Create pipeline for neoepitope prediction

### ISSUE THREAD

**Issue by hammer** [hammerlab/biokepi#47]
What needs to get done first:
- [x] [Create topiary target](https://github.com/hammerlab/biokepi/issues/37)
- [x] [Add HLA typing](https://github.com/hammerlab/biokepi/issues/33)

**Comment by smondet** [comment]
## [Epidisco!](https://github.com/hammerlab/epidisco)

![](http://67.media.tumblr.com/7ed2dab49586c00956a0bb491d1b5538/tumblr_mlnzx84Ur21qzw1qyo1_500.gif)
