### ISSUE TITLE
Support running with GRCh38 and/or hg38

### ISSUE THREAD

**Issue by julia326** [hammerlab/biokepi#479]

**Comment by smondet** [comment]
B38 and hg19 are there, but some URLs may be broken, have you tried? which ones did fail?
https://github.com/hammerlab/biokepi/blob/master/src/run_environment/reference_genome.ml#L172

**Comment by armish** [comment]
@julia326: FYI: I gave `b38` a try yesterday and looks like all URLs are working fine; you should be good to go with either of these.

**Comment by julia326** [comment]
@armish thanks for checking it out!
