### ISSUE TITLE
output compressed VCFs from variant callers

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/biokepi#57]
Most tools that work with VCFs (e.g. `varcode`) can also work with gzipped compressed VCFs, which of course tend to be way smaller. We should compress the VCFs outputted by our pipelines by default.

The best way to do this would be with the `bgzip` tool from `tabix`, but plain `gzip` would also work. See: http://blastedbio.blogspot.com/2011/11/bgzf-blocked-bigger-better-gzip.html

**Comment by smondet** [comment]
We already have `bgzip` and `tabix` by the way https://github.com/hammerlab/biokepi/blob/master/src/lib/samtools.ml#L47

@ihodes Cycledash still wants only `.vcf` files right? or is there some (de)compression already implementated by PyVFC or so?

**Comment by timodonnell** [comment]
Yeah, if it's using pyvcf, it should automatically work with compressed
vcfs.

**Comment by arahuja** [comment]
Sounds this was resolved? If anyone wants compressed VCFs you can use the zip elements of biokepi?
