### ISSUE TITLE
Example script for local somatic variant calling

### ISSUE THREAD

**Issue by iskandr** [hammerlab/biokepi#71]
I wish there was an example script which

(1) ran locally without configuration 
(2) allowed me to align reads & call somatic variants from local FASTQs
(3) didn't require editing any OCaml code to specify input/output filenames

**Comment by timodonnell** [comment]
+1 I would also find this helpful

**Comment by smondet** [comment]
Please try there: https://github.com/hammerlab/biokepi#getting-started

**Comment by smondet** [comment]
The `biokepi-demo` is mostly that.
