### ISSUE TITLE
Reorganizing modules into pipelines

### ISSUE THREAD

**Issue by arahuja** [hammerlab/biokepi#79]
@rleonid suggested re-organizing some of the code here into more easily discoverable pipelines.  I'd be interested in the best Ocaml strategy for doing this, but in the meantime I'll lay out some of the hierarchy for the tools that have been added.

#### DNA
Basic pipeline:
{aligners} x {BAM preprocessing} x {variant calling}

aligners: fastq -> BAM = {`BWA`, `bwa-mem`, `bowtie` (not in biokepi yet), `SNAP` (not in biokepi yet)
BAM preprocessing: BAM -> BAM = {`GATK Indel Realignment`, `GATK BQSR`, `Picard MarkDuplicates`}
Germline variant calling: BAM -> VCF = {`GATK Unified Genotyper`, `GATK HaplotypeCaller`}
Somatic variant calling: (BAM, BAM) -> VCF = {`Mutect`, `Strelka`, `Varscan2`, `SomaticSniper`}

#### RNA
Basic pipeline:
{aligners} x {quantification}

aligners: fastq -> BAM = {`Hisat`, `Star`}
quantification: fastq/BAM -> Custom text file = {`Cufflinks`, `Stringtie`, `Kallisto`}

**Comment by rleonid** [comment]
Thanks for the description @arahuja. I think a general solution will end up functorizing the arguments, but let me see what would be a suitable simple first step.

**Comment by ihodes** [comment]
Does this differ in some way from the pipeline API in pipeline.ml? This is nicely modeled in the GADT there (just needs some serious documentation: https://github.com/hammerlab/biokepi/issues/96)

**Comment by arahuja** [comment]
@ihodes Yes, very similar, but that is specific for variant calling vs i.e. RNA quantification.  I think documentation or code reorganization would also help explain what tools are for what.

**Comment by ihodes** [comment]
Cool, that clarifies things for me. Makes sense.
